services:
  servicebus-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servicebus-db
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD}' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    depends_on:
      servicebus-db:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./Config.json
        target: /ServiceBus_Emulator/ConfigFiles/Config.json
        read_only: true
    environment:
      SQL_SERVER: ${SQL_SERVER}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "5672:5672"

  servicebus-explorer:
    image: ghcr.io/tombiddulph/service-bus-emulator-explorer:0.1.0
    container_name: servicebus-explorer
    depends_on:
      - servicebus-emulator
    environment:
      - SERVICE_BUS_CONNECTION_STRING=${SERVICE_BUS_CONNECTION_STRING}
    ports:
      - "8081:80"