services:
  coordinator-service:
    image: coordinator-service:1.0.0
    container_name: coordinator-service
    ports:
      - "${COORDINATOR_SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      FRONTEND_URL: ${FRONTEND_URL}

  receiver-service:
    image: receiver-service:1.0.0
    container_name: receiver-service
    ports:
      - "${RECEIVER_SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      COORDINATOR_URL: ${COORDINATOR_URL}
      TIMESTAMP_TOLERANCE: ${TIMESTAMP_TOLERANCE}
    depends_on:
      - coordinator-service

  sender-service:
    image: sender-service:1.0.0
    container_name: sender-service
    ports:
      - "${SENDER_SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      COORDINATOR_URL: ${COORDINATOR_URL}
      WEBHOOK_RECEIVER_URL: ${WEBHOOK_RECEIVER_URL}
    depends_on:
      - coordinator-service

  webhook-tester:
    image: webhook-tester:1.0.0
    container_name: webhook-tester
    ports:
      - "${WEBHOOK_TESTER_PORT}:${WEBHOOK_TESTER_INTERNAL_PORT}"
    environment:
      COORDINATOR_URL: ${FRONTEND_COORDINATOR_URL}
      RECEIVER_URL: ${FRONTEND_RECEIVER_URL}
      SENDER_URL: ${FRONTEND_SENDER_URL}
    depends_on:
      - coordinator-service
      - receiver-service
      - sender-service