services:
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka-payment-notification
    ports:
      - "${KAFKA_PORT}:9096"
      - "${KAFKA_CONTROLLER_PORT}:9097"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:${KAFKA_CONTROLLER_PORT}"
      KAFKA_LISTENERS: "PLAINTEXT://:9096,CONTROLLER://:${KAFKA_CONTROLLER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:${KAFKA_PORT}"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data_payment_notification:/var/lib/kafka/data
    networks:
      - app-network-payment-notification

  mysql:
    image: mysql:9.6.0
    container_name: mysql-db-payment-notification
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data_payment_notification:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network-payment-notification

volumes:
  mysql_data_payment_notification:
  kafka_data_payment_notification:

networks:
  app-network-payment-notification:
    driver: bridge