services:
  mongodb:
    image: mongo:8.3.7-noble
    container_name: product-poc-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - springboot-network
    command: mongod --bind_ip_all --auth

volumes:
  mongo_data:
    driver: local

networks:
  springboot-network:
    driver: bridge